
import "./globals.css";

export const metadata = {
  title: "PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body>
        {children}
      </body>
    </html>
  );
}
