
import "./globals.css";
import Analytics from "../Components/Analytics";

export const metadata = {
  title: "PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  

    <html lang="en" className="overflow-x-hidden">
      <head>
        {/* Google tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-RZ9GNECQLV"></script>
        <script dangerouslySetInnerHTML={{__html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RZ9GNECQLV');
        `}} />
      </head>
      <body>
        <Analytics /> 
        {children}
      </body>
    </html>
  );
}
